backend:
  name: git-gateway
  branch: master

media_folder: data/content/posts/img
public_folder: static

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    editor:
     preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "date", widget: "string" }
      - { label: "Excerpt", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
